import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import TanstackProvider from '@/lib/tanstack-provider';

import './globals.css';

import { cn } from '@/lib/utils';
import { Footer, Nav } from '@/components';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'min-h-screen bg-foreground text-secondary font-sans antialiased',
          fontSans.variable
        )}
      >
        <TanstackProvider>
          <Nav />
          {children}
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  );
}
